from __future__ import annotations

from .models import Rule, Severity

DEFAULT_RULES: list[Rule] = [
    Rule(
        id="private-key",
        title="Private key header",
        description="PEM private key header",
        severity=Severity.critical,
        pattern=r"-----BEGIN (?:RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----",
        multiline=True,
        tags=("key", "pem"),
    ),
    Rule(
        id="aws-access-key-id",
        title="AWS Access Key ID",
        description="AWS Access Key ID (AKIA/ASIA...)",
        severity=Severity.high,
        pattern=r"\b(AKIA|ASIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASCA|AKIAR)[0-9A-Z]{16}\b",
        tags=("aws",),
    ),
    Rule(
        id="github-token",
        title="GitHub token",
        description="GitHub tokens (ghp_/github_pat_...)",
        severity=Severity.high,
        pattern=r"\b(ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{20,}\b",
        tags=("github",),
    ),
    Rule(
        id="slack-token",
        title="Slack token",
        description="Slack tokens (xoxb/xoxa/...)",
        severity=Severity.high,
        pattern=r"\b(xox[baprs]-[0-9A-Za-z-]{10,48})\b",
        tags=("slack",),
    ),
    Rule(
        id="telegram-bot-token",
        title="Telegram bot token",
        description="Telegram bot tokens: <digits>:<base64url-ish>",
        severity=Severity.high,
        pattern=r"\b\d{6,12}:[A-Za-z0-9_-]{30,}\b",
        tags=("telegram",),
    ),
    Rule(
        id="google-api-key",
        title="Google API key",
        description="Google API key (AIza...)",
        severity=Severity.high,
        pattern=r"\bAIza[0-9A-Za-z\-_]{30,}\b",
        tags=("google",),
    ),
    Rule(
        id="sendgrid-key",
        title="SendGrid API key",
        description="SendGrid API key (SG.<base64>.<base64>)",
        severity=Severity.high,
        pattern=r"\bSG\.[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{20,}\b",
        tags=("sendgrid",),
    ),
    Rule(
        id="stripe-secret",
        title="Stripe secret key",
        description="Stripe secret key (sk_live_...)",
        severity=Severity.high,
        pattern=r"\bsk_live_[0-9a-zA-Z]{20,}\b",
        tags=("stripe",),
    ),
    Rule(
        id="discord-token",
        title="Discord token",
        description="Discord token (three base64url segments)",
        severity=Severity.high,
        pattern=r"\b[MN][A-Za-z0-9_-]{23,}\.[A-Za-z0-9_-]{6,}\.[A-Za-z0-9_-]{27,}\b",
        tags=("discord",),
    ),
    Rule(
        id="jwt",
        title="JWT",
        description="JWT (three base64url segments)",
        severity=Severity.medium,
        pattern=r"\beyJ[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\.[A-Za-z0-9_\-]+\b",
        tags=("jwt",),
    ),
    Rule(
        id="generic-credential",
        title="Generic credential assignment",
        description="Suspicious assignment like api_key=..., token: ..., password=...",
        severity=Severity.medium,
        pattern=r"(?i)\b(api[_-]?key|secret|token|password|passwd|access[_-]?token|client[_-]?secret)\b\s*[:=]\s*['\"]?([A-Za-z0-9_\-\/\+=]{8,})",
        tags=("generic",),
    ),
]
